// app/features/research-workspace/components/agent-review-panel.tsx
"use client";

import {
  IconAlertTriangle,
  IconCheck,
  IconGitBranch,
  IconPencil,
  IconSparkles,
  IconX,
} from "@tabler/icons-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useI18n } from "../../../i18n/provider";
import type { AgentJobStatus } from "../../../plugins/agent-contracts";
import { AGENT_STAGE_LABELS, isJobTerminal } from "../../../plugins/agent-contracts";
import type { GraphPatchOperation, PluginGraphPatch } from "../../../plugins/contracts";
import { normalizePluginGraphPatch } from "../../../plugins/workspace";
import type { PdfCompileResult } from "../../../platform/agent-client";
import { getPdfJobStatus, reviewPdfPatch } from "../../../platform/agent-client";

/** 逐项审阅决策 / Per-operation review decision. */
export type ReviewDecision = {
  accept: boolean;
  /** 接受时的就地编辑（add-node.title / add-edge.note） */
  edits?: Record<string, string>;
};

/** 操作主语摘要，用于列表展示 / Operation subject summary for display. */
export function operationSubject(operation: GraphPatchOperation): string {
  switch (operation.op) {
    case "add-node":
      return operation.node.title;
    case "add-edge":
      return `${operation.edge.source} → ${operation.edge.target}`;
    case "update-node":
      return operation.nodeId;
    case "update-edge":
      return operation.edgeId;
  }
}

/** 纯函数：按决策过滤操作并应用就地编辑，返回子集 patch；全部拒绝时返回 null。 */
export function buildAcceptedPatch(
  patch: PluginGraphPatch,
  decisions: Record<number, ReviewDecision>,
): PluginGraphPatch | null {
  const operations = patch.operations
    .map((operation, index) => {
      const decision = decisions[index];
      if (decision && !decision.accept) return null;
      if (!decision?.edits) return operation;
      if (operation.op === "add-node" && decision.edits.title !== undefined) {
        return { ...operation, node: { ...operation.node, title: decision.edits.title } };
      }
      if (operation.op === "add-edge" && decision.edits.note !== undefined) {
        return { ...operation, edge: { ...operation.edge, note: decision.edits.note } };
      }
      return operation;
    })
    .filter((operation): operation is GraphPatchOperation => operation !== null);
  if (operations.length === 0) return null;
  return { ...patch, operations };
}

/** 纯函数：统计被接受的操作数 / Count accepted operations. */
export function countAccepted(decisions: Record<number, ReviewDecision>, total: number): number {
  let count = 0;
  for (let index = 0; index < total; index += 1) {
    if (!decisions[index] || decisions[index].accept) count += 1;
  }
  return count;
}

/**
 * 阶段 3：Agent 提案审阅面板。
 * 只负责展示 GraphPatch 操作、逐项裁决与就地编辑；
 * 接受后发出 review_patch 命令并通过 onApply 交付过滤后的补丁，由宿主应用。
 */
export function AgentReviewPanel({
  jobId,
  compileResult,
  compileError,
  onClose,
  onApply,
  onReject,
}: {
  jobId: string;
  compileResult?: PdfCompileResult | null;
  compileError?: string;
  onClose: () => void;
  onApply: (patch: PluginGraphPatch) => void;
  onReject: () => void;
}) {
  const { t } = useI18n();
  const [status, setStatus] = useState<AgentJobStatus | null>(null);
  const [decisions, setDecisions] = useState<Record<number, ReviewDecision>>({});
  const [error, setError] = useState("");
  const [applying, setApplying] = useState(false);

  useEffect(() => {
    let mounted = true;
    void getPdfJobStatus(jobId)
      .then((snapshot) => {
        if (mounted) setStatus(snapshot);
      })
      .catch((loadError) => {
        if (mounted) setError(loadError instanceof Error ? loadError.message : String(loadError));
      });
    return () => {
      mounted = false;
    };
  }, [jobId]);

  const patch = useMemo(() => {
    if (!status?.result) return null;
    return normalizePluginGraphPatch(status.result);
  }, [status]);

  const counts = useMemo(() => {
    const byOp: Record<string, number> = {};
    for (const operation of patch?.operations ?? []) {
      byOp[operation.op] = (byOp[operation.op] ?? 0) + 1;
    }
    return byOp;
  }, [patch]);

  const setDecision = useCallback((index: number, decision: ReviewDecision) => {
    setDecisions((current) => ({ ...current, [index]: decision }));
  }, []);

  const setEdit = useCallback((index: number, field: string, value: string) => {
    setDecisions((current) => {
      const previous = current[index] ?? { accept: true };
      return { ...current, [index]: { ...previous, edits: { ...previous.edits, [field]: value } } };
    });
  }, []);

  const acceptAll = useCallback(() => {
    setDecisions(
      Object.fromEntries(
        (patch?.operations ?? []).map((_, index) => [
          index,
          { accept: true, edits: decisions[index]?.edits },
        ]),
      ),
    );
  }, [decisions, patch?.operations]);

  const applySelected = useCallback(async () => {
    if (!patch || applying) return;
    const accepted = buildAcceptedPatch(patch, decisions);
    setApplying(true);
    setError("");
    try {
      await reviewPdfPatch(jobId, true);
      if (accepted) onApply(accepted);
      else onReject();
    } catch (applyError) {
      setError(applyError instanceof Error ? applyError.message : String(applyError));
      setApplying(false);
    }
  }, [applying, decisions, jobId, onApply, onReject, patch]);

  const rejectAll = useCallback(async () => {
    if (applying) return;
    setApplying(true);
    setError("");
    try {
      await reviewPdfPatch(jobId, false);
      onReject();
    } catch (rejectError) {
      setError(rejectError instanceof Error ? rejectError.message : String(rejectError));
      setApplying(false);
    }
  }, [applying, jobId, onReject]);

  const acceptedCount = patch ? countAccepted(decisions, patch.operations.length) : 0;
  const settled = status ? isJobTerminal(status.state) : false;

  return (
    <div className="fixed inset-0 z-[97] grid place-items-center bg-ink/10 backdrop-blur-[2px]">
      <section className="grid h-[min(680px,calc(100vh-32px))] w-[min(960px,calc(100vw-32px))] grid-cols-1 overflow-hidden rounded-[7px] border border-ink/30 bg-paper shadow-[0_18px_60px_rgba(30,32,35,.15)] md:grid-cols-[minmax(0,1fr)_300px]">
        <div className="flex min-h-0 flex-col border-b border-ink/15 md:border-b-0 md:border-r">
          <header className="flex items-start justify-between border-b border-ink/15 px-7 py-5">
            <div>
              <span className="font-sans text-[8px] uppercase tracking-[0.18em] text-blue">
                {t("agent.eyebrow")}
              </span>
              <h2 className="mt-1 flex items-center gap-2 font-serif text-[21px]">
                <IconSparkles size={19} stroke={1.35} />
                {t("agent.reviewTitle")}
              </h2>
              <p className="mt-1 max-w-[560px] font-serif text-[10px] leading-[1.5] text-ink/50">
                {t("agent.reviewSubtitle")}
              </p>
            </div>
            <button className="icon-quiet" onClick={onClose} aria-label={t("menu.close")}>
              <IconX size={18} stroke={1.35} />
            </button>
          </header>

          <div className="min-h-0 flex-1 overflow-y-auto px-6 py-5">
            {!patch ? (
              <p className="grid min-h-[280px] place-items-center rounded-[6px] border border-dashed border-ink/20 bg-canvas px-5 text-center font-serif text-[11px] text-ink/45">
                {status ? t("workspace.noPatch") : `${t("agent.starting")} ${jobId.slice(0, 12)}…`}
              </p>
            ) : (
              <div className="space-y-2">
                {patch.operations.map((operation, index) => {
                  const decision = decisions[index] ?? { accept: true };
                  const editing = decision.accept;
                  const isNode = operation.op === "add-node";
                  const isEdge = operation.op === "add-edge";
                  const OpIcon = isNode ? IconCheck : isEdge ? IconGitBranch : IconPencil;
                  return (
                    <article
                      key={`${operation.op}-${index}`}
                      className={`rounded-[5px] border p-3 transition ${
                        editing ? "border-blue/35 bg-blue-soft/50" : "border-ink/15 bg-canvas opacity-60"
                      }`}
                    >
                      <div className="flex items-start gap-3">
                        <span
                          className={`mt-0.5 grid size-7 shrink-0 place-items-center rounded-full border ${
                            editing ? "border-blue/40 bg-blue-soft text-blue" : "border-ink/20 text-ink/45"
                          }`}
                        >
                          <OpIcon size={14} stroke={1.5} />
                        </span>
                        <div className="min-w-0 flex-1">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="rounded-[3px] bg-blue-soft px-1.5 py-0.5 font-sans text-[7px] uppercase tracking-[0.1em] text-blue">
                              {t(
                                operation.op === "add-node"
                                  ? "agent.op.addNode"
                                  : operation.op === "add-edge"
                                    ? "agent.op.addEdge"
                                    : operation.op === "update-node"
                                      ? "agent.op.updateNode"
                                      : "agent.op.updateEdge",
                              )}
                            </span>
                            <span className="rounded-[3px] bg-ink/8 px-1.5 py-0.5 font-sans text-[7px] uppercase tracking-[0.1em] text-ink/55">
                              {isNode
                                ? operation.node.type
                                : isEdge
                                  ? operation.edge.type
                                  : operation.op}
                            </span>
                          </div>
                          <p className="mt-1.5 truncate font-serif text-[12px]" title={operationSubject(operation)}>
                            {operationSubject(operation)}
                          </p>
                          {isNode && operation.node.body && (
                            <p className="mt-1 line-clamp-2 font-serif text-[9px] leading-[1.5] text-ink/50">
                              {operation.node.body}
                            </p>
                          )}
                          {editing && isNode && (
                            <label className="dialog-field mt-2">
                              {t("agent.op.title")}
                              <input
                                value={decision.edits?.title ?? operation.node.title}
                                onChange={(event) => setEdit(index, "title", event.target.value)}
                              />
                            </label>
                          )}
                          {editing && isEdge && (
                            <label className="dialog-field mt-2">
                              {t("agent.op.note")}
                              <input
                                value={decision.edits?.note ?? operation.edge.note ?? ""}
                                onChange={(event) => setEdit(index, "note", event.target.value)}
                              />
                            </label>
                          )}
                        </div>
                        <div className="flex shrink-0 items-center gap-1" role="group" aria-label={t("agent.decision.accept")}>
                          <button
                            className={`rounded-[4px] border px-2.5 py-1 font-sans text-[8px] transition ${
                              decision.accept
                                ? "border-blue bg-blue text-paper"
                                : "border-ink/20 text-ink/55 hover:border-blue hover:text-blue"
                            }`}
                            onClick={() => setDecision(index, { accept: true, edits: decision.edits })}
                          >
                            {t("agent.decision.accept")}
                          </button>
                          <button
                            className={`rounded-[4px] border px-2.5 py-1 font-sans text-[8px] transition ${
                              !decision.accept
                                ? "border-alert bg-alert text-paper"
                                : "border-ink/20 text-ink/55 hover:border-alert hover:text-alert"
                            }`}
                            onClick={() => setDecision(index, { accept: false })}
                          >
                            {t("agent.decision.reject")}
                          </button>
                        </div>
                      </div>
                    </article>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        <aside className="flex min-h-0 flex-col overflow-y-auto bg-canvas p-5">
          <div className="flex items-center gap-2 text-blue">
            <IconSparkles size={17} stroke={1.35} />
            <h3 className="font-serif text-[14px]">{t("agent.reviewTitle")}</h3>
          </div>
          {status && (
            <p className="mt-2 font-serif text-[9px] leading-[1.5] text-ink/50">
              {status.pdfPath.split(/[\\/]/).pop()}
            </p>
          )}
          {patch && (
            <p className="mt-1 font-serif text-[10px] leading-[1.5] text-ink/60">
              {patch.operations.length} {t("agent.operations")} · {patch.summary}
            </p>
          )}
          {counts && (
            <div className="mt-3 flex flex-wrap gap-1">
              {Object.entries(counts).map(([op, count]) => (
                <span key={op} className="rounded-[3px] bg-ink/8 px-1.5 py-0.5 font-sans text-[7px] text-ink/60">
                  {op} × {count}
                </span>
              ))}
            </div>
          )}

          <div className="mt-5 space-y-2">
            <button
              className="button-primary w-full justify-center"
              disabled={!patch || applying || settled}
              onClick={() => void applySelected()}
            >
              <IconCheck size={15} stroke={1.35} />
              {t("agent.applySelected", { count: acceptedCount })}
            </button>
            <button
              className="button-secondary w-full justify-center"
              disabled={!patch || applying || settled}
              onClick={() => void rejectAll()}
            >
              <IconX size={15} stroke={1.35} />
              {t("agent.rejectAll")}
            </button>
            <button
              className="button-secondary w-full justify-center"
              disabled={!patch || applying}
              onClick={acceptAll}
            >
              {t("agent.acceptAll")}
            </button>
          </div>

          {error && (
            <p className="mt-3 flex items-start gap-2 rounded-[4px] border border-alert/40 bg-alert/5 px-3 py-2 font-serif text-[9px] leading-[1.5] text-alert">
              <IconAlertTriangle size={13} stroke={1.5} className="mt-0.5 shrink-0" />
              <span className="min-w-0 break-words">{error}</span>
            </p>
          )}

          {compileError && (
            <p className="mt-3 flex items-start gap-2 rounded-[4px] border border-alert/40 bg-alert/5 px-3 py-2 font-serif text-[9px] leading-[1.5] text-alert">
              <IconAlertTriangle size={13} stroke={1.5} className="mt-0.5 shrink-0" />
              <span className="min-w-0 break-words">{t("agent.compileFailed", { error: compileError })}</span>
            </p>
          )}

          {compileResult && (
            <div className="mt-5 border-t border-ink/15 pt-5">
              <h4 className="font-sans text-[8px] uppercase tracking-[0.16em] text-ink/45">
                {t("agent.compiling")}
              </h4>
              <dl className="mt-3 space-y-2">
                <div className="rounded-[4px] border border-ink/12 bg-paper px-3 py-2">
                  <dt className="font-sans text-[7px] uppercase tracking-[0.12em] text-ink/45">
                    {t("agent.compileBlockHashes", { count: Object.keys(compileResult.compile.blockHashes).length })}
                  </dt>
                  <dd className="mt-1 truncate font-mono text-[8px] text-ink/70" title={compileResult.compile.contentRootHash}>
                    {t("agent.compileRootHash", { hash: compileResult.compile.contentRootHash.slice(0, 12) })}
                  </dd>
                </div>
                <div className="rounded-[4px] border border-ink/12 bg-paper px-3 py-2">
                  <dt className={`font-sans text-[7px] uppercase tracking-[0.12em] ${compileResult.compile.violations.length ? "text-alert" : "text-olive"}`}>
                    {compileResult.compile.violations.length
                      ? t("agent.compileInvariants", { count: compileResult.compile.violations.length })
                      : t("agent.compileInvariantsOk")}
                  </dt>
                  <dd className="mt-1 font-mono text-[8px] text-ink/60">
                    {compileResult.logicChain.summary}
                  </dd>
                </div>
                <div className="rounded-[4px] border border-ink/12 bg-paper px-3 py-2">
                  <dt className="font-sans text-[7px] uppercase tracking-[0.12em] text-ink/45">
                    {t("agent.logicChain", { score: compileResult.logicChain.score.toFixed(2) })}
                  </dt>
                  <dd className="mt-1 font-mono text-[8px] text-ink/60">
                    {compileResult.logicChain.nodeIds.length} nodes · {compileResult.logicChain.edgeIds.length} edges
                  </dd>
                </div>
                <div className="rounded-[4px] border border-ink/12 bg-paper px-3 py-2">
                  <dt className={`font-sans text-[7px] uppercase tracking-[0.12em] ${compileResult.contradictions.cycles.length ? "text-alert" : "text-olive"}`}>
                    {compileResult.contradictions.cycles.length
                      ? t("agent.contradictions", { count: compileResult.contradictions.cycles.length })
                      : t("agent.contradictionsOk")}
                  </dt>
                  <dd className="mt-1 font-mono text-[8px] text-ink/60">
                    {t("agent.beliefs", { value: compileResult.beliefs.meanNetBelief.toFixed(2) })}
                  </dd>
                </div>
              </dl>
            </div>
          )}

          <p className="mt-auto pt-5 font-serif text-[8px] text-ink/35">
            {status ? AGENT_STAGE_LABELS[status.state] : ""}
          </p>
        </aside>
      </section>
    </div>
  );
}

// src/vue/components/AgentReviewPanel.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import type { MessageKey } from "../../../app/i18n/catalog";
import { isJobTerminal, type AgentJobStage } from "../../../app/plugins/agent-contracts";
import { normalizePluginGraphPatch } from "../../../app/plugins/workspace";
import { getPdfJobStatus, reviewPdfPatch } from "../../../app/platform/agent-client";
import {
  buildAcceptedPatch,
  countAccepted,
  operationSubject,
  usePanelI18n,
  type AgentReviewPanelProps,
  type ReviewDecision,
} from "./panel-types";

const props = defineProps<AgentReviewPanelProps>();
const { t } = usePanelI18n();
const status = ref<Awaited<ReturnType<typeof getPdfJobStatus>> | null>(null);
const decisions = ref<Record<number, ReviewDecision>>({});
const error = ref("");
const applying = ref(false);

const patch = computed(() => {
  if (!status.value?.result) return null;
  return normalizePluginGraphPatch(status.value.result);
});
const acceptedCount = computed(() =>
  patch.value ? countAccepted(decisions.value, patch.value.operations.length) : 0,
);
const settled = computed(() => (status.value ? isJobTerminal(status.value.state) : false));
const counts = computed(() => {
  const result: Record<string, number> = {};
  for (const operation of patch.value?.operations ?? []) {
    result[operation.op] = (result[operation.op] ?? 0) + 1;
  }
  return result;
});

const stageLabel = (stage: AgentJobStage) => t(`agent.stage.${stage}` as MessageKey);
const opLabel = (op: string) => {
  const key: Record<string, MessageKey> = {
    "add-node": "agent.op.addNode",
    "add-edge": "agent.op.addEdge",
    "update-node": "agent.op.updateNode",
    "update-edge": "agent.op.updateEdge",
  };
  return t(key[op] ?? "agent.op.updateNode");
};
const decisionFor = (index: number): ReviewDecision => decisions.value[index] ?? { accept: false };
const setDecision = (index: number, decision: ReviewDecision) => {
  decisions.value = { ...decisions.value, [index]: decision };
};
const setEdit = (index: number, field: string, value: string) => {
  const previous = decisionFor(index);
  setDecision(index, {
    ...previous,
    edits: { ...previous.edits, [field]: value },
  });
};
const acceptAll = () => {
  decisions.value = Object.fromEntries(
    (patch.value?.operations ?? []).map((_, index) => [
      index,
      { accept: true, edits: decisions.value[index]?.edits },
    ]),
  );
};

let requestSerial = 0;
watch(
  () => props.jobId,
  async (jobId) => {
    const serial = ++requestSerial;
    status.value = null;
    decisions.value = {};
    error.value = "";
    try {
      const snapshot = await getPdfJobStatus(jobId);
      if (serial === requestSerial) status.value = snapshot;
    } catch (cause) {
      if (serial === requestSerial) error.value = cause instanceof Error ? cause.message : String(cause);
    }
  },
  { immediate: true },
);

const applySelected = async () => {
  if (!patch.value || applying.value) return;
  const accepted = buildAcceptedPatch(patch.value, decisions.value);
  applying.value = true;
  error.value = "";
  try {
    if (accepted) props.onApply(accepted);
    else props.onReject();
    await reviewPdfPatch(props.jobId, accepted !== null);
  } catch (cause) {
    if (accepted) props.onRollback();
    error.value = cause instanceof Error ? cause.message : String(cause);
    applying.value = false;
  }
};

const rejectAll = async () => {
  if (applying.value) return;
  applying.value = true;
  error.value = "";
  try {
    await reviewPdfPatch(props.jobId, false);
    props.onReject();
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : String(cause);
    applying.value = false;
  }
};
</script>

<template>
  <div class="fixed inset-0 z-[97] grid place-items-center bg-ink/10 backdrop-blur-[2px]">
    <section class="grid h-[min(680px,calc(100vh-32px))] w-[min(960px,calc(100vw-32px))] grid-cols-1 overflow-hidden rounded-[7px] border border-ink/30 bg-paper shadow-[0_18px_60px_rgba(30,32,35,.15)] md:grid-cols-[minmax(0,1fr)_300px]">
      <div class="flex min-h-0 flex-col border-b border-ink/15 md:border-b-0 md:border-r">
        <header class="flex items-start justify-between border-b border-ink/15 px-7 py-5">
          <div>
            <span class="font-sans text-[8px] uppercase tracking-[0.18em] text-blue">{{ t('agent.eyebrow') }}</span>
            <h2 class="mt-1 flex items-center gap-2 font-serif text-[21px]"><span aria-hidden="true">✦</span>{{ t('agent.reviewTitle') }}</h2>
            <p class="mt-1 max-w-[560px] font-serif text-[10px] leading-[1.5] text-ink/50">{{ t('agent.reviewSubtitle') }}</p>
          </div>
          <button class="icon-quiet" @click="props.onClose" :aria-label="t('menu.close')">×</button>
        </header>

        <div class="min-h-0 flex-1 overflow-y-auto px-6 py-5">
          <p v-if="!patch" class="grid min-h-[280px] place-items-center rounded-[6px] border border-dashed border-ink/20 bg-canvas px-5 text-center font-serif text-[11px] text-ink/45">
            {{ status ? t('workspace.noPatch') : `${t('agent.starting')} ${props.jobId.slice(0, 12)}…` }}
          </p>
          <div v-else class="space-y-2">
            <article
              v-for="(operation, index) in patch.operations"
              :key="`${operation.op}-${index}`"
              class="rounded-[5px] border p-3 transition"
              :class="decisionFor(index).accept ? 'border-blue/35 bg-blue-soft/50' : 'border-ink/15 bg-canvas opacity-60'"
            >
              <div class="flex items-start gap-3">
                <span class="mt-0.5 grid size-7 shrink-0 place-items-center rounded-full border" :class="decisionFor(index).accept ? 'border-blue/40 bg-blue-soft text-blue' : 'border-ink/20 text-ink/45'">
                  {{ operation.op === 'add-node' ? '✓' : operation.op === 'add-edge' ? '↗' : '✎' }}
                </span>
                <div class="min-w-0 flex-1">
                  <div class="flex flex-wrap items-center gap-2">
                    <span class="rounded-[3px] bg-blue-soft px-1.5 py-0.5 font-sans text-[7px] uppercase tracking-[0.1em] text-blue">{{ opLabel(operation.op) }}</span>
                    <span class="rounded-[3px] bg-ink/8 px-1.5 py-0.5 font-sans text-[7px] uppercase tracking-[0.1em] text-ink/55">{{ operation.op === 'add-node' ? operation.node.type : operation.op === 'add-edge' ? operation.edge.type : operation.op }}</span>
                  </div>
                  <p class="mt-1.5 truncate font-serif text-[12px]" :title="operationSubject(operation)">{{ operationSubject(operation) }}</p>
                  <p v-if="operation.op === 'add-node' && operation.node.body" class="mt-1 line-clamp-2 font-serif text-[9px] leading-[1.5] text-ink/50">{{ operation.node.body }}</p>
                  <label v-if="decisionFor(index).accept && operation.op === 'add-node'" class="dialog-field mt-2">{{ t('agent.op.title') }}<input :value="decisionFor(index).edits?.title ?? operation.node.title" @input="setEdit(index, 'title', ($event.target as HTMLInputElement).value)" /></label>
                  <label v-if="decisionFor(index).accept && operation.op === 'add-edge'" class="dialog-field mt-2">{{ t('agent.op.note') }}<input :value="decisionFor(index).edits?.note ?? operation.edge.note ?? ''" @input="setEdit(index, 'note', ($event.target as HTMLInputElement).value)" /></label>
                </div>
                <div class="flex shrink-0 items-center gap-1" role="group" :aria-label="t('agent.decision.accept')">
                  <button class="rounded-[4px] border px-2.5 py-1 font-sans text-[8px] transition" :class="decisionFor(index).accept ? 'border-blue bg-blue text-paper' : 'border-ink/20 text-ink/55 hover:border-blue hover:text-blue'" @click="setDecision(index, { accept: true, edits: decisionFor(index).edits })">{{ t('agent.decision.accept') }}</button>
                  <button class="rounded-[4px] border px-2.5 py-1 font-sans text-[8px] transition" :class="!decisionFor(index).accept ? 'border-alert bg-alert text-paper' : 'border-ink/20 text-ink/55 hover:border-alert hover:text-alert'" @click="setDecision(index, { accept: false })">{{ t('agent.decision.reject') }}</button>
                </div>
              </div>
            </article>
          </div>
        </div>
      </div>

      <aside class="flex min-h-0 flex-col overflow-y-auto bg-canvas p-5">
        <div class="flex items-center gap-2 text-blue"><span aria-hidden="true">✦</span><h3 class="font-serif text-[14px]">{{ t('agent.reviewTitle') }}</h3></div>
        <p v-if="status" class="mt-2 font-serif text-[9px] leading-[1.5] text-ink/50">{{ status.pdfPath.split(/[\\/]/).pop() }}</p>
        <p v-if="patch" class="mt-1 font-serif text-[10px] leading-[1.5] text-ink/60">{{ patch.operations.length }} {{ t('agent.operations') }} · {{ patch.summary }}</p>
        <div v-if="patch" class="mt-3 flex flex-wrap gap-1"><span v-for="(count, op) in counts" :key="op" class="rounded-[3px] bg-ink/8 px-1.5 py-0.5 font-sans text-[7px] text-ink/60">{{ op }} · {{ count }}</span></div>
        <div class="mt-5 space-y-2">
          <button class="button-primary w-full justify-center" :disabled="!patch || applying || settled" @click="void applySelected()">✓ {{ t('agent.applySelected', { count: acceptedCount }) }}</button>
          <button class="button-secondary w-full justify-center" :disabled="!patch || applying || settled" @click="void rejectAll()">× {{ t('agent.rejectAll') }}</button>
          <button class="button-secondary w-full justify-center" :disabled="!patch || applying" @click="acceptAll">{{ t('agent.acceptAll') }}</button>
        </div>
        <p v-if="error" class="mt-3 flex items-start gap-2 rounded-[4px] border border-alert/40 bg-alert/5 px-3 py-2 font-serif text-[9px] leading-[1.5] text-alert">⚠ <span class="min-w-0 break-words">{{ error }}</span></p>
        <p v-if="props.compileError" class="mt-3 flex items-start gap-2 rounded-[4px] border border-alert/40 bg-alert/5 px-3 py-2 font-serif text-[9px] leading-[1.5] text-alert">⚠ <span class="min-w-0 break-words">{{ t('agent.compileFailed', { error: props.compileError }) }}</span></p>
        <div v-if="props.compileResult" class="mt-5 border-t border-ink/15 pt-5">
          <h4 class="font-sans text-[8px] uppercase tracking-[0.16em] text-ink/45">{{ t('agent.compiling') }}</h4>
          <dl class="mt-3 space-y-2">
            <div class="rounded-[4px] border border-ink/12 bg-paper px-3 py-2"><dt class="font-sans text-[7px] uppercase tracking-[0.12em] text-ink/45">{{ t('agent.compileBlockHashes', { count: Object.keys(props.compileResult.compile.blockHashes).length }) }}</dt><dd class="mt-1 truncate font-mono text-[8px] text-ink/70">{{ props.compileResult.compile.contentRootHash.slice(0, 12) }}</dd></div>
            <div class="rounded-[4px] border border-ink/12 bg-paper px-3 py-2"><dt class="font-sans text-[7px] uppercase tracking-[0.12em]" :class="props.compileResult.compile.violations.length ? 'text-alert' : 'text-olive'">{{ props.compileResult.compile.violations.length ? t('agent.compileInvariants', { count: props.compileResult.compile.violations.length }) : t('agent.compileInvariantsOk') }}</dt><dd class="mt-1 font-mono text-[8px] text-ink/60">{{ props.compileResult.logicChain.summary }}</dd></div>
            <div class="rounded-[4px] border border-ink/12 bg-paper px-3 py-2"><dt class="font-sans text-[7px] uppercase tracking-[0.12em] text-ink/45">{{ t('agent.logicChain', { score: props.compileResult.logicChain.score.toFixed(2) }) }}</dt><dd class="mt-1 font-mono text-[8px] text-ink/60">{{ props.compileResult.logicChain.nodeIds.length }} nodes · {{ props.compileResult.logicChain.edgeIds.length }} edges</dd></div>
          </dl>
        </div>
        <p class="mt-auto pt-5 font-serif text-[8px] text-ink/35">{{ status ? stageLabel(status.state) : '' }}</p>
      </aside>
    </section>
  </div>
</template>

<style scoped>
/* Shared panel visual tokens remain in app/globals.css. */
</style>
