// app/features/research-workspace/components/plugin-store-dialog.tsx
"use client";

import {
  IconBox,
  IconCheck,
  IconCode,
  IconDatabaseImport,
  IconFolder,
  IconPlayerPlay,
  IconPlugConnected,
  IconRefresh,
  IconShieldCheck,
  IconTrash,
  IconUpload,
  IconWorld,
  IconX,
} from "@tabler/icons-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useI18n } from "../../../i18n/provider";
import { builtInPluginCatalog } from "../../../plugins/catalog";
import {
  latestCompatiblePlugins,
  pluginCompatibility,
  pluginKey,
} from "../../../plugins/identity";
import { usePluginHost } from "../../../plugins/plugin-host";
import { pluginReference } from "../../../plugins/contracts";
import {
  listenForMycDrops,
  pickMycFiles,
  runAnalysisPlugin,
} from "../../../plugins/tauri-client";

type StoreFilter = "all" | "installed" | "runtime" | "workspace" | "locales";

/**
 * Desktop-backed plugin store; package extraction and execution stay in Rust.
 * 桌面端插件商店；包解压和执行始终留在 Rust 边界内。
 */
export function PluginStoreDialog({ onClose }: { onClose: () => void }) {
  const { t } = useI18n();
  const {
    installedPlugins: installed,
    activePluginKeys,
    loading,
    error: hostError,
    refresh,
    install,
    setPluginEnabled,
    enableAll,
    removeIncompatible,
  } = usePluginHost();
  const [filter, setFilter] = useState<StoreFilter>("all");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [selfTestResults, setSelfTestResults] = useState<
    Record<string, { status: "running" | "success" | "error"; text: string }>
  >({});
  const latestKeys = useMemo(
    () => new Set(latestCompatiblePlugins(installed).map(pluginKey)),
    [installed],
  );
  const hostBusy = busy || loading;
  const incompatibleCount = useMemo(
    () => installed.filter((plugin) => !pluginCompatibility(plugin).compatible).length,
    [installed],
  );

  // ── 拖放状态 / Drag-drop state ──
  const [dragOver, setDragOver] = useState(false);
  const dragCounter = useRef(0);

  const installPaths = useCallback(
    async (paths: string[]) => {
      const mycPaths = paths.filter((p) => p.toLowerCase().endsWith(".myc"));
      if (mycPaths.length === 0) return;
      setBusy(true);
      setMessage("");
      let ok = 0;
      const errors: string[] = [];
      for (const path of mycPaths) {
        try {
          await install(path);
          ok++;
        } catch (error) {
          errors.push(error instanceof Error ? error.message : String(error));
        }
      }
      if (errors.length === 0) {
        setMessage(t("plugins.installedToast", { count: ok }));
      } else {
        setMessage(
          ok > 0
            ? `${t("plugins.installedToast", { count: ok })} · ${errors.join("; ")}`
            : errors.join("; "),
        );
      }
      setBusy(false);
    },
    [install, t],
  );

  // ── Tauri 原生拖放监听 (webview 级别) / Tauri native drop listener (webview-level) ──
  useEffect(() => {
    let cancelled = false;
    let stop: () => void = () => undefined;
    void listenForMycDrops(async (paths) => {
      if (paths.length === 0) return;
      await installPaths(paths);
    }).then((unlisten) => {
      if (cancelled) unlisten();
      else stop = unlisten;
    });
    return () => {
      cancelled = true;
      stop();
    };
  }, [installPaths]);

  // ── 点击浏览按钮 / Browse button handler ──
  const handleBrowse = useCallback(async () => {
    const paths = await pickMycFiles();
    if (paths && paths.length > 0) {
      await installPaths(paths);
    }
  }, [installPaths]);

  // ── HTML5 拖放事件处理 / HTML5 drag-drop event handlers ──
  const handleDragEnter = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    dragCounter.current++;
    setDragOver(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    dragCounter.current--;
    if (dragCounter.current <= 0) {
      dragCounter.current = 0;
      setDragOver(false);
    }
  }, []);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
  }, []);

  const handleDrop = useCallback(
    async (e: React.DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
      dragCounter.current = 0;
      setDragOver(false);

      // 尝试从 Tauri 原生事件中提取路径；回退到 HTML5 File API
      const files = e.dataTransfer?.files;
      if (!files || files.length === 0) return;

      const paths: string[] = [];
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        // Tauri v2 在 File 对象上暴露 path 属性
        const filePath = (file as unknown as { path?: string }).path;
        if (filePath) {
          paths.push(filePath);
        }
      }

      if (paths.length > 0) {
        await installPaths(paths);
      } else {
        setMessage(t("plugins.dropNoPaths"));
      }
    },
    [installPaths, t],
  );

  const visibleInstalled = useMemo(
    () =>
      filter === "runtime"
        ? installed.filter((plugin) => plugin.runtime)
        : filter === "workspace"
          ? installed.filter((plugin) => plugin.workspace)
          : filter === "locales"
            ? installed.filter((plugin) => plugin.locales?.length)
        : installed,
    [filter, installed],
  );

  return (
    <div className="fixed inset-0 z-[96] grid place-items-center bg-ink/10 backdrop-blur-[2px]">
      <section
        className="flex h-[650px] w-[880px] flex-col overflow-hidden rounded-[7px] border border-ink/30 bg-paper shadow-[0_18px_60px_rgba(30,32,35,.15)]"
        role="dialog"
        aria-modal="true"
        aria-labelledby="plugin-store-title"
      >
        <header className="flex shrink-0 items-start justify-between border-b border-ink/15 px-7 py-5">
          <div>
            <span className="font-sans text-[8px] uppercase tracking-[0.18em] text-blue">
              {t("plugins.eyebrow")}
            </span>
            <h2 id="plugin-store-title" className="mt-1 font-serif text-[21px]">
              {t("plugins.title")}
            </h2>
            <p className="mt-1 font-serif text-[10px] text-ink/50">
              {t("plugins.subtitle")}
            </p>
          </div>
          <div className="flex items-center gap-1">
            {incompatibleCount > 0 && (
              <button
                className="button-secondary mr-2 px-3 text-alert"
                disabled={hostBusy}
                onClick={async () => {
                  if (!window.confirm(t("plugins.removeIncompatibleConfirm", { count: incompatibleCount }))) {
                    return;
                  }
                  setBusy(true);
                  try {
                    const removed = await removeIncompatible();
                    setMessage(t("plugins.removedIncompatibleToast", { count: removed }));
                  } catch (error) {
                    setMessage(error instanceof Error ? error.message : String(error));
                  } finally {
                    setBusy(false);
                  }
                }}
              >
                <IconTrash size={14} stroke={1.4} />
                {t("plugins.removeIncompatible", { count: incompatibleCount })}
              </button>
            )}
            <button className="button-secondary mr-2 px-3" onClick={enableAll} disabled={hostBusy}>
              <IconCheck size={14} stroke={1.4} />
              {t("plugins.enableAll")}
            </button>
            <button className="icon-quiet" onClick={() => void refresh()} aria-label={t("plugins.refresh")}>
              <IconRefresh className={hostBusy ? "animate-spin" : ""} size={17} stroke={1.35} />
            </button>
            <button className="icon-quiet" onClick={onClose} aria-label={t("plugins.close")}>
              <IconX size={18} stroke={1.35} />
            </button>
          </div>
        </header>

        <div className="grid min-h-0 flex-1 grid-cols-[210px_minmax(0,1fr)]">
          <aside className="border-r border-ink/15 bg-canvas p-4">
            <nav className="space-y-1" aria-label="Plugin filters">
              {([
                ["all", t("plugins.all"), IconBox],
                ["installed", t("plugins.installed"), IconCheck],
                ["runtime", t("plugins.runtime"), IconCode],
                ["workspace", t("plugins.workspace"), IconFolder],
                ["locales", t("plugins.locales"), IconWorld],
              ] as const).map(([value, label, Icon]) => (
                <button
                  key={value}
                  className={`flex w-full items-center gap-3 rounded-[4px] px-3 py-2.5 text-left font-serif text-[12px] transition ${
                    filter === value ? "bg-blue-soft text-blue" : "hover:bg-ink/5"
                  }`}
                  onClick={() => setFilter(value)}
                >
                  <Icon size={17} stroke={1.35} />
                  {label}
                </button>
              ))}
            </nav>
            <div className="mt-6 rounded-[5px] border border-blue/20 bg-blue-soft p-3">
              <div className="flex items-center gap-2 text-blue">
                <IconShieldCheck size={17} stroke={1.35} />
                <span className="font-serif text-[11px]">{t("plugins.runtime")}</span>
              </div>
              <p className="mt-2 font-serif text-[9px] leading-[1.45] text-ink/55">
                {t("plugins.runtimeHint")}
              </p>
            </div>
          </aside>

          <div className="min-h-0 overflow-y-auto p-6">
            <div
              className={`rounded-[6px] border-2 border-dashed px-5 py-5 transition-colors ${
                dragOver
                  ? "border-blue bg-blue/5"
                  : hostBusy
                    ? "border-ink/15 bg-canvas opacity-60"
                    : "border-ink/25 bg-canvas hover:border-ink/40"
              }`}
              onDragEnter={handleDragEnter}
              onDragLeave={handleDragLeave}
              onDragOver={handleDragOver}
              onDrop={handleDrop}
              role="button"
              tabIndex={0}
              aria-label={t("plugins.dropTitle")}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") handleBrowse();
              }}
            >
              <div className="flex items-center gap-3">
                <IconDatabaseImport
                  size={24}
                  stroke={1.25}
                  className={dragOver ? "text-blue" : "text-blue/70"}
                />
                <div className="flex-1">
                  <p className="font-serif text-[13px]">
                    {dragOver ? t("plugins.dropActive") : t("plugins.dropTitle")}
                  </p>
                  <p className="mt-0.5 font-serif text-[9px] text-ink/50">
                    {t("plugins.dropHint")}
                  </p>
                </div>
                <button
                  type="button"
                  className={`flex items-center gap-1.5 rounded-[5px] border px-3.5 py-2 font-serif text-[11px] transition ${
                    hostBusy
                      ? "cursor-not-allowed border-ink/15 text-ink/30"
                      : "border-blue/40 bg-blue-soft text-blue hover:bg-blue/15"
                  }`}
                  disabled={hostBusy}
                  onClick={(e) => {
                    e.stopPropagation();
                    void handleBrowse();
                  }}
                >
                  <IconUpload size={15} stroke={1.4} />
                  {t("plugins.browseFiles")}
                </button>
              </div>
            </div>

            {(message || hostError) && (
              <div className="mt-3 rounded-[4px] border border-blue/20 bg-blue-soft px-3 py-2 font-serif text-[10px] text-blue">
                {message || hostError}
              </div>
            )}

            {filter === "all" && (
              <section className="mt-6">
                <h3 className="font-sans text-[8px] uppercase tracking-[0.16em] text-ink/45">
                  {t("plugins.builtInCatalog")}
                </h3>
                <div className="mt-2 grid grid-cols-2 gap-3">
                  {builtInPluginCatalog.map((plugin) => (
                    <article key={plugin.id} className="rounded-[5px] border border-ink/15 p-3">
                      <div className="flex items-start gap-3">
                        <IconPlugConnected size={18} stroke={1.35} className="mt-0.5 text-ink/60" />
                        <div className="min-w-0 flex-1">
                          <p className="font-serif text-[12px]">{plugin.name}</p>
                          <p className="mt-1 line-clamp-2 font-serif text-[9px] leading-[1.4] text-ink/50">
                            {plugin.description}
                          </p>
                        </div>
                        <span className="font-sans text-[7px] uppercase tracking-[0.12em] text-ink/40">
                          {plugin.status}
                        </span>
                      </div>
                    </article>
                  ))}
                </div>
              </section>
            )}

            <section className="mt-6">
              <h3 className="font-sans text-[8px] uppercase tracking-[0.16em] text-ink/45">
                {t("plugins.installed")} · .myc
              </h3>
              <div className="mt-2 space-y-2">
                {visibleInstalled.length === 0 && (
                  <p className="rounded-[5px] border border-ink/15 px-4 py-6 text-center font-serif text-[10px] text-ink/45">
                    {t("plugins.noInstalled")}
                  </p>
                )}
                {visibleInstalled.map((plugin) => {
                  const key = pluginKey(plugin);
                  const isEnabled = activePluginKeys.has(key);
                  const compatibility = pluginCompatibility(plugin);
                  const superseded = compatibility.compatible && !latestKeys.has(key);
                  return (
                    <article key={key} className="rounded-[5px] border border-ink/18 p-4">
                      <div className="flex items-start gap-3">
                        {plugin.runtime ? (
                          <IconCode size={19} stroke={1.35} className="mt-0.5 text-blue" />
                        ) : (
                          <IconBox size={19} stroke={1.35} className="mt-0.5 text-ink/60" />
                        )}
                        <div className="min-w-0 flex-1">
                          <div className="flex items-center gap-2">
                            <h4 className="font-serif text-[13px]">{plugin.manifest.metadata.name}</h4>
                            <span className="font-sans text-[7px] uppercase tracking-[0.12em] text-ink/40">
                              {plugin.manifest.kind} · {plugin.manifest.metadata.version}
                            </span>
                          </div>
                          <p className="mt-1 font-serif text-[9px] leading-[1.45] text-ink/50">
                            {plugin.manifest.metadata.description}
                          </p>
                          <p className="mt-2 font-sans text-[8px] text-ink/45">
                            {plugin.manifest.spec.capabilities.join(" · ")}
                            {plugin.runtime ? ` · ${plugin.runtime.language}/wasm` : ""}
                          </p>
                          {!compatibility.compatible && (
                            <p className="mt-1 font-serif text-[8px] text-alert">
                              {compatibility.issues.map((issue, index) => (
                                <span key={issue.key}>
                                  {index > 0 && " · "}
                                  {t(issue.key, issue.params ?? {})}
                                </span>
                              ))}
                            </p>
                          )}
                          {superseded && (
                            <p className="mt-1 font-serif text-[8px] text-ink/40">
                              {t("plugins.superseded")}
                            </p>
                          )}
                          {plugin.runtime && (
                            <p
                              className="mt-1 truncate font-mono text-[7px] text-ink/40"
                              title={`${t("plugins.sha256")}: ${plugin.runtime.entrySha256}`}
                            >
                              {t("plugins.sha256")} · {plugin.runtime.entrySha256}
                            </p>
                          )}
                          {selfTestResults[key] && (
                            <p
                              className={`mt-2 rounded-[4px] border px-2.5 py-2 font-serif text-[9px] ${
                                selfTestResults[key].status === "error"
                                  ? "border-alert/25 bg-alert/5 text-alert"
                                  : selfTestResults[key].status === "running"
                                    ? "border-blue/20 bg-blue-soft text-blue"
                                    : "border-ink/15 bg-canvas text-ink/65"
                              }`}
                              role="status"
                              aria-live="polite"
                            >
                              {selfTestResults[key].text}
                            </p>
                          )}
                          {plugin.workspace && (
                            <p className="mt-1 font-serif text-[8px] text-ink/45">
                              {(plugin.manifest.spec.contributes?.commands ?? [])
                                .map((command) => command.label)
                                .join(" · ")}
                            </p>
                          )}
                          {plugin.locales && plugin.locales.length > 0 && (
                            <p className="mt-1 font-serif text-[8px] text-ink/45">
                              {plugin.locales
                                .map((locale) => `${locale.name} (${locale.locale})`)
                                .join(" · ")}
                            </p>
                          )}
                        </div>
                        <div className="flex gap-2">
                          {plugin.runtime && (
                            <button
                              className="button-secondary px-3"
                              disabled={!isEnabled || hostBusy}
                              title={!isEnabled ? t("plugins.enableToTest") : undefined}
                              onClick={async () => {
                                setBusy(true);
                                setSelfTestResults((current) => ({
                                  ...current,
                                  [key]: { status: "running", text: t("plugins.selfTestRunning") },
                                }));
                                try {
                                  const result = await runAnalysisPlugin(
                                    pluginReference(plugin),
                                    { operation: "self-test" },
                                    "analysis.run",
                                  );
                                  setSelfTestResults((current) => ({
                                    ...current,
                                    [key]: {
                                      status: "success",
                                      text: `${t("plugins.selfTestPassed", {
                                        duration: result.durationMs,
                                        fuel: result.fuelConsumed,
                                      })} ${JSON.stringify(result.output)}`,
                                    },
                                  }));
                                } catch (error) {
                                  setSelfTestResults((current) => ({
                                    ...current,
                                    [key]: {
                                      status: "error",
                                      text: error instanceof Error ? error.message : String(error),
                                    },
                                  }));
                                } finally {
                                  setBusy(false);
                                }
                              }}
                            >
                              <IconPlayerPlay size={14} stroke={1.4} />
                              {t("plugins.selfTest")}
                            </button>
                          )}
                          <button
                            className={isEnabled ? "button-primary px-3" : "button-secondary px-3"}
                            disabled={!compatibility.compatible || hostBusy}
                            onClick={() => setPluginEnabled(plugin, !isEnabled)}
                          >
                            {isEnabled ? t("plugins.enabled") : t("plugins.enable")}
                          </button>
                        </div>
                      </div>
                    </article>
                  );
                })}
              </div>
            </section>
          </div>
        </div>
      </section>
    </div>
  );
}

// src/vue/components/PluginStoreDialog.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";
import { builtInPluginCatalog } from "../../../app/plugins/catalog";
import {
  latestCompatiblePlugins,
  pluginCompatibility,
  pluginKey,
} from "../../../app/plugins/identity";
import { pluginReference } from "../../../app/plugins/contracts";
import {
  listenForMycDrops,
  pickMycFiles,
  runAnalysisPlugin,
} from "../../../app/plugins/tauri-client";
import type { InstalledMycPlugin } from "../../../app/plugins/contracts";
import { usePluginHost } from "../runtime/plugin-host";
import { usePanelI18n, type PluginStoreDialogProps } from "./panel-types";
import PluginStoreItem from "./PluginStoreItem.vue";

const props = defineProps<PluginStoreDialogProps>();
const { t } = usePanelI18n();
const pluginHost = usePluginHost();
type StoreFilter = "all" | "installed" | "runtime" | "workspace" | "locales";
const filter = ref<StoreFilter>("all");
const installed = computed(() => pluginHost.installedPlugins);
const activePluginKeys = computed(() => pluginHost.activePluginKeys);
const loading = computed(() => pluginHost.loading);
const hostError = computed(() => pluginHost.error);
const busy = ref(false);
const message = ref("");
const dragOver = ref(false);
const dragCounter = ref(0);
const selfTestResults = ref<Record<string, { status: "running" | "success" | "error"; text: string }>>({});

const latestKeys = computed(() => new Set(latestCompatiblePlugins(installed.value).map(pluginKey)));
const incompatibleCount = computed(() => installed.value.filter((plugin) => !pluginCompatibility(plugin).compatible).length);
const hostBusy = computed(() => busy.value || loading.value);
const visibleInstalled = computed(() => filter.value === "runtime"
  ? installed.value.filter((plugin) => plugin.runtime)
  : filter.value === "workspace"
    ? installed.value.filter((plugin) => plugin.workspace)
    : filter.value === "locales"
      ? installed.value.filter((plugin) => plugin.locales?.length)
      : installed.value);

const refresh = pluginHost.refresh;
const setPluginEnabled = pluginHost.setPluginEnabled;
const enableAll = pluginHost.enableAll;
const removeIncompatible = pluginHost.removeIncompatible;
const install = pluginHost.install;
const installPaths = async (paths: string[]) => {
  const mycPaths = paths.filter((path) => path.toLowerCase().endsWith(".myc"));
  if (!mycPaths.length) return;
  busy.value = true;
  message.value = "";
  let ok = 0;
  const errors: string[] = [];
  for (const path of mycPaths) {
    try { await install(path); ok += 1; } catch (cause) { errors.push(cause instanceof Error ? cause.message : String(cause)); }
  }
  message.value = errors.length === 0 ? t("plugins.installedToast", { count: ok }) : ok > 0 ? `${t("plugins.installedToast", { count: ok })} · ${errors.join("; ")}` : errors.join("; ");
  busy.value = false;
};
const handleBrowse = async () => {
  const paths = await pickMycFiles();
  if (paths?.length) await installPaths(paths);
};
const handleDrop = async (event: DragEvent) => {
  event.preventDefault();
  event.stopPropagation();
  dragCounter.value = 0;
  dragOver.value = false;
  const files = event.dataTransfer?.files;
  if (!files?.length) return;
  const paths: string[] = [];
  for (let index = 0; index < files.length; index += 1) {
    const path = (files[index] as File & { path?: string }).path;
    if (path) paths.push(path);
  }
  if (paths.length) await installPaths(paths);
  else message.value = t("plugins.dropNoPaths");
};
const runSelfTest = async (plugin: InstalledMycPlugin) => {
  const key = pluginKey(plugin);
  busy.value = true;
  selfTestResults.value = { ...selfTestResults.value, [key]: { status: "running", text: t("plugins.selfTestRunning") } };
  try {
    const result = await runAnalysisPlugin(pluginReference(plugin), { operation: "self-test" }, "analysis.run");
    selfTestResults.value = { ...selfTestResults.value, [key]: { status: "success", text: `${t("plugins.selfTestPassed", { duration: result.durationMs, fuel: result.fuelConsumed })} ${JSON.stringify(result.output)}` } };
  } catch (cause) {
    selfTestResults.value = { ...selfTestResults.value, [key]: { status: "error", text: cause instanceof Error ? cause.message : String(cause) } };
  } finally { busy.value = false; }
};

let disposeDropListener: (() => void) | undefined;
onMounted(async () => {
  await refresh();
  disposeDropListener = await listenForMycDrops((paths) => { void installPaths(paths); });
});
onUnmounted(() => disposeDropListener?.());
</script>

<template>
  <div class="fixed inset-0 z-[96] grid place-items-center bg-ink/10 backdrop-blur-[2px]">
    <section class="flex h-[650px] w-[880px] flex-col overflow-hidden rounded-[7px] border border-ink/30 bg-paper shadow-[0_18px_60px_rgba(30,32,35,.15)]" role="dialog" aria-modal="true" aria-labelledby="plugin-store-title">
      <header class="flex shrink-0 items-start justify-between border-b border-ink/15 px-7 py-5"><div><span class="font-sans text-[8px] uppercase tracking-[0.18em] text-blue">{{ t('plugins.eyebrow') }}</span><h2 id="plugin-store-title" class="mt-1 font-serif text-[21px]">{{ t('plugins.title') }}</h2><p class="mt-1 font-serif text-[10px] text-ink/50">{{ t('plugins.subtitle') }}</p></div><div class="flex items-center gap-1"><button v-if="incompatibleCount" class="button-secondary mr-2 px-3 text-alert" :disabled="hostBusy" @click="void removeIncompatible().then((count) => { message = t('plugins.removedIncompatibleToast', { count }) }).catch((cause) => { message = cause instanceof Error ? cause.message : String(cause) })">⌫ {{ t('plugins.removeIncompatible', { count: incompatibleCount }) }}</button><button class="button-secondary mr-2 px-3" :disabled="hostBusy" @click="enableAll">✓ {{ t('plugins.enableAll') }}</button><button class="icon-quiet" :disabled="hostBusy" @click="void refresh()" :aria-label="t('plugins.refresh')">↻</button><button class="icon-quiet" @click="props.onClose" :aria-label="t('plugins.close')">×</button></div></header>
      <div class="grid min-h-0 flex-1 grid-cols-[210px_minmax(0,1fr)]">
        <aside class="border-r border-ink/15 bg-canvas p-4"><nav class="space-y-1" aria-label="Plugin filters"><button v-for="entry in [['all', t('plugins.all')], ['installed', t('plugins.installed')], ['runtime', t('plugins.runtime')], ['workspace', t('plugins.workspace')], ['locales', t('plugins.locales')]] as Array<[StoreFilter, string]>" :key="entry[0]" class="flex w-full items-center gap-3 rounded-[4px] px-3 py-2.5 text-left font-serif text-[12px] transition" :class="filter === entry[0] ? 'bg-blue-soft text-blue' : 'hover:bg-ink/5'" @click="filter = entry[0]">▣ {{ entry[1] }}</button></nav><div class="mt-6 rounded-[5px] border border-blue/20 bg-blue-soft p-3"><div class="flex items-center gap-2 text-blue">▣ <span class="font-serif text-[11px]">{{ t('plugins.runtime') }}</span></div><p class="mt-2 font-serif text-[9px] leading-[1.45] text-ink/55">{{ t('plugins.runtimeHint') }}</p></div></aside>
        <div class="min-h-0 overflow-y-auto p-6">
          <div class="rounded-[6px] border-2 border-dashed px-5 py-5 transition-colors" :class="dragOver ? 'border-blue bg-blue/5' : hostBusy ? 'border-ink/15 bg-canvas opacity-60' : 'border-ink/25 bg-canvas hover:border-ink/40'" role="button" tabindex="0" :aria-label="t('plugins.dropTitle')" @dragenter.prevent="dragCounter++; dragOver = true" @dragleave.prevent="dragCounter--; if (dragCounter <= 0) { dragCounter = 0; dragOver = false }" @dragover.prevent @drop="void handleDrop($event)"><div class="flex items-center gap-3"><span class="text-2xl text-blue/70">⇧</span><div class="flex-1"><p class="font-serif text-[13px]">{{ dragOver ? t('plugins.dropActive') : t('plugins.dropTitle') }}</p><p class="mt-0.5 font-serif text-[9px] text-ink/50">{{ t('plugins.dropHint') }}</p></div><button type="button" class="flex items-center gap-1.5 rounded-[5px] border border-blue/40 bg-blue-soft px-3.5 py-2 font-serif text-[11px] text-blue transition" :disabled="hostBusy" @click.stop="void handleBrowse()">↑ {{ t('plugins.browseFiles') }}</button></div></div>
          <div v-if="message || hostError" class="mt-3 rounded-[4px] border border-blue/20 bg-blue-soft px-3 py-2 font-serif text-[10px] text-blue">{{ message || hostError }}</div>
          <section v-if="filter === 'all'" class="mt-6">
            <h3 class="font-sans text-[8px] uppercase tracking-[0.16em] text-ink/45">{{ t('plugins.builtInCatalog') }}</h3>
            <div class="mt-2 grid grid-cols-2 gap-3">
              <PluginStoreItem
                v-for="plugin in builtInPluginCatalog"
                :key="plugin.id"
                :name="plugin.name"
                :version="plugin.version"
                :kind="plugin.category"
                :description="plugin.description"
              >
                <template #icon><span class="mt-0.5 text-ink/60">◈</span></template>
                <template #status>
                  <span class="font-sans text-[7px] uppercase tracking-[0.12em] text-ink/40">{{ plugin.status }}</span>
                </template>
              </PluginStoreItem>
            </div>
          </section>
          <section class="mt-6">
            <h3 class="font-sans text-[8px] uppercase tracking-[0.16em] text-ink/45">{{ t('plugins.installed') }} · .myc</h3>
            <div class="mt-2 space-y-2">
              <p v-if="visibleInstalled.length === 0" class="rounded-[5px] border border-ink/15 px-4 py-6 text-center font-serif text-[10px] text-ink/45">{{ t('plugins.noInstalled') }}</p>
              <PluginStoreItem
                v-for="plugin in visibleInstalled"
                :key="pluginKey(plugin)"
                :name="plugin.manifest.metadata.name"
                :version="plugin.manifest.metadata.version"
                :kind="plugin.manifest.kind"
                :description="plugin.manifest.metadata.description"
              >
                <template #icon><span class="mt-0.5 text-blue">{{ plugin.runtime ? '⌘' : '◈' }}</span></template>
                <p class="mt-2 font-sans text-[8px] text-ink/45">{{ plugin.manifest.spec.capabilities.join(' · ') }}{{ plugin.runtime ? ` · ${plugin.runtime.language}/wasm` : '' }}</p>
                <p v-if="!pluginCompatibility(plugin).compatible" class="mt-1 font-serif text-[8px] text-alert">{{ pluginCompatibility(plugin).issues.map((issue) => t(issue.key, issue.params ?? {})).join(' · ') }}</p>
                <p v-if="pluginCompatibility(plugin).compatible && !latestKeys.has(pluginKey(plugin))" class="mt-1 font-serif text-[8px] text-ink/40">{{ t('plugins.superseded') }}</p>
                <p v-if="plugin.runtime" class="mt-1 truncate font-mono text-[7px] text-ink/40">{{ t('plugins.sha256') }} · {{ plugin.runtime.entrySha256 }}</p>
                <p
                  v-if="selfTestResults[pluginKey(plugin)]"
                  class="mt-2 rounded-[4px] border px-2.5 py-2 font-serif text-[9px]"
                  :class="selfTestResults[pluginKey(plugin)].status === 'error' ? 'border-alert/25 bg-alert/5 text-alert' : selfTestResults[pluginKey(plugin)].status === 'running' ? 'border-blue/20 bg-blue-soft text-blue' : 'border-ink/15 bg-canvas text-ink/65'"
                  role="status"
                  aria-live="polite"
                >
                  {{ selfTestResults[pluginKey(plugin)].text }}
                </p>
                <template #actions>
                  <button v-if="plugin.runtime" class="button-secondary px-3" :disabled="!activePluginKeys.has(pluginKey(plugin)) || hostBusy" :title="!activePluginKeys.has(pluginKey(plugin)) ? t('plugins.enableToTest') : undefined" @click="void runSelfTest(plugin)">▶ {{ t('plugins.selfTest') }}</button>
                  <button class="px-3" :class="activePluginKeys.has(pluginKey(plugin)) ? 'button-primary' : 'button-secondary'" :disabled="!pluginCompatibility(plugin).compatible || hostBusy" @click="setPluginEnabled(plugin, !activePluginKeys.has(pluginKey(plugin)))">{{ activePluginKeys.has(pluginKey(plugin)) ? t('plugins.enabled') : t('plugins.enable') }}</button>
                </template>
              </PluginStoreItem>
            </div>
          </section>
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
/* Shared plugin-store visual tokens remain in app/globals.css. */
</style>
